[project]
name = "polars-internals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "notebook>=7.3.2",
    "numpy>=2.2.1",
    "polars[all]>=1.18.0",
]

[dependency-groups]
dev = [
    "faker>=33.1.0",
    "memory-profiler>=0.61.0",
]
